/**
 * GENERATED by tools/build-character-atlas.mjs — do not edit by hand.
 *
 * The Kenney "Blocky Characters" rig, baked once. All 18 shipped characters
 * have byte-identical geometry and UVs (the tool asserts it on every run), so
 * this is the ONLY character mesh in the game: 216 vertices, 72 triangles,
 * six parts, four customisable zones.
 *
 * UVs are pre-folded into one period and pre-divided by the atlas grid, so a
 * consumer picks an outfit by ADDING a cell offset — no second geometry, no
 * second material, no second draw call.
 *
 * Atlas: 4x3 cells of 160px in client/public/c/kenney-chars.png (65.3 KB).
 */

/** Cells across the atlas. */
export const ATLAS_COLS = 4;
/** Cells down the atlas. */
export const ATLAS_ROWS = 3;
export const ATLAS_CELL_PX = 160;
/** Fetched lazily, after the menu is interactive. Never bundled. */
export const ATLAS_URL = 'c/kenney-chars.png';

/** Model height in metres, feet at y=0. Scale by PLAYER_HEIGHT / this. */
export const RIG_HEIGHT = 2.7;

/** The six meshes the GLB actually contains, in baked order. */
export const RIG_PART_NAMES = ["leg-left","leg-right","torso","arm-left","arm-right","head"] as const;

/** Pivot of each part, metres, model space. Indexed by RIG_PART_NAMES order. */
export const RIG_PIVOTS: readonly (readonly [number, number, number])[] = [
  [0.2000, 1.0000, 0.0000],
  [-0.2000, 1.0000, 0.0000],
  [0.0000, 0.7000, 0.0000],
  [0.4000, 1.8000, -0.1000],
  [-0.4000, 1.8000, -0.1000],
  [0.0000, 1.9000, 0.0000],
];

/** One outfit donor: a cell in the atlas. */
export interface RigDonor { readonly key: string; readonly name: string; }
export const RIG_DONORS: readonly RigDonor[] = [
  { key: 'm', name: 'Marine' },
  { key: 'j', name: 'Enforcer' },
  { key: 'b', name: 'Ranger' },
  { key: 'o', name: 'Wrench' },
  { key: 'k', name: 'Timber' },
  { key: 'f', name: 'Diver' },
  { key: 'l', name: 'Revenant' },
  { key: 'r', name: 'Cultist' },
  { key: 'g', name: 'Sentry' },
  { key: 'h', name: 'Warden' },
  { key: 'd', name: 'Gilded' },
  { key: 'n', name: 'Medic' },
];

const POS_Q = 1 / 1024;
const UV_Q = 1 / 65535;

function unpack(b64: string): Uint8Array {
  const bin = atob(b64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}
function i16(b64: string): Int16Array {
  const u = unpack(b64);
  return new Int16Array(u.buffer, u.byteOffset, u.byteLength >> 1);
}
function u16(b64: string): Uint16Array {
  const u = unpack(b64);
  return new Uint16Array(u.buffer, u.byteOffset, u.byteLength >> 1);
}

/** Baked attribute arrays. Built on first call, then cached. */
export interface RigArrays {
  /** 216 * 3 metres, feet at y = 0, +Z forward. */
  readonly position: Float32Array;
  /** 216 * 2, already inside atlas cell 0. Add the donor offset. */
  readonly uv: Float32Array;
  /** 216 * 3 — the point this vertex's part rotates about. */
  readonly pivot: Float32Array;
  /** 216 — 0 head, 1 torso, 2 arms, 3 legs. */
  readonly zone: Float32Array;
  /** 216 — baked flat-face shade, matching the voxel mesher's ramp. */
  readonly shade: Float32Array;
  readonly index: Uint16Array;
}

let cached: RigArrays | null = null;

export function rigArrays(): RigArrays {
  if (cached !== null) return cached;
  const qp = i16('AAAAAM0AmgEAADP/mgEAAM0AmgEAADP/AAAAAM0AAAAAADP/mgEABDP/AAAABM0AmgEABM0AAAAABM0AmgEABDP/AAAABDP/mgEABM0AAAAAAM0AmgEAAM0AAAAAAM0AmgEABM0AAAAABM0AmgEABM0AmgEAADP/mgEABDP/mgEAADP/mgEABM0AmgEAAM0AAAAAAM0AAAAABDP/AAAAADP/AAAABDP/AAAAAM0AAAAABM0AAAAABDP/mgEAADP/AAAAADP/mgEAADP/AAAABDP/mgEABDP/Zv4AAM0AAAAAADP/AAAAAM0AAAAAADP/Zv4AAM0AZv4AADP/AAAABDP/Zv4ABM0AAAAABM0AZv4ABM0AAAAABDP/Zv4ABDP/AAAABM0AZv4AAM0AAAAAAM0AZv4AAM0AAAAABM0AZv4ABM0AAAAABM0AAAAAADP/AAAABDP/AAAAADP/AAAABM0AAAAAAM0AZv4AAM0AZv4ABDP/Zv4AADP/Zv4ABDP/Zv4AAM0AZv4ABM0AZv4ABDP/AAAAADP/Zv4AADP/AAAAADP/Zv4ABDP/AAAABDP/mgEABDMBZv4ABM3+mgEABM3+Zv4ABM3+mgEABDMBZv4ABDMBZv6aB83+mgEABM3+Zv4ABM3+mgEABM3+Zv6aB83+mgGaB83+mgGaBzMBmgEABM3+mgGaB83+mgEABM3+mgGaBzMBmgEABDMBmgGaBzMBZv4ABDMBmgEABDMBZv4ABDMBmgGaBzMBZv6aBzMBZv6aB83+mgGaBzMBmgGaB83+mgGaBzMBZv6aB83+Zv6aBzMBZv4ABM3+Zv6aBzMBZv6aB83+Zv6aBzMBZv4ABM3+Zv4ABDMBMwOaB2YAMwMzA83+MwOaB83+MwMzA83+MwOaB2YAMwMzA2YAmgEzA83+MwOaB83+MwMzA83+MwOaB83+mgEzA83+mgGaB83+MwOaB2YAmgEzA2YAMwMzA2YAmgEzA2YAMwOaB2YAmgGaB2YAmgEzA2YAmgGaB83+mgEzA83+mgGaB83+mgEzA2YAmgGaB2YAMwOaB83+mgGaB2YAMwOaB2YAmgGaB2YAMwOaB83+mgGaB83+mgEzA2YAMwMzA83+MwMzA2YAMwMzA83+mgEzA2YAmgEzA83+Zv6aB2YAZv4zA83+Zv6aB83+Zv4zA83+Zv6aB2YAZv4zA2YAzfwzA83+Zv6aB83+Zv4zA83+Zv6aB83+zfwzA83+zfyaB83+Zv6aB83+zfyaB2YAZv6aB2YAzfyaB2YAZv6aB83+zfyaB83+zfwzA2YAZv4zA83+Zv4zA2YAZv4zA83+zfwzA2YAzfwzA83+zfwzA2YAzfyaB83+zfwzA83+zfyaB83+zfwzA2YAzfyaB2YAZv6aB2YAzfwzA2YAZv4zA2YAzfwzA2YAZv6aB2YAzfyaB2YAZv6aB5oBZv7NCmb+Zv6aB2b+Zv7NCmb+Zv6aB5oBZv7NCpoBZv7NCmb+mgHNCpoBmgHNCmb+mgHNCpoBZv7NCmb+Zv7NCpoBmgHNCpoBmgGaB2b+mgHNCmb+mgGaB2b+mgHNCpoBmgGaB5oBmgHNCpoBZv6aB5oBmgGaB5oBZv6aB5oBmgHNCpoBZv7NCpoBZv7NCmb+mgGaB2b+Zv6aB2b+mgGaB2b+Zv7NCmb+mgHNCmb+mgGaB5oBZv6aB2b+mgGaB2b+Zv6aB2b+mgGaB5oBZv6aB5oB');
  const qv = i16('zQAABAAAzQAABAAAzQAABAAAzQAABAAAzQAABAAAzQAABAAAzQAABAAAzQAABAAAzQAABAAAzQAABAAAzQAABAAAzQAABAAAzQAABAAAzQAABAAAzQAABAAAzQAABAAAzQAABAAAzQAABAAAzQAABAAAzQAABAAAzQAABAAAzQAABAAAzQAABAAAzQAABAAAzQAABAAAzQAABAAAzQAABAAAzQAABAAAzQAABAAAzQAABAAAzQAABAAAzQAABAAAzQAABAAAzQAABAAAzQAABAAAzQAABAAAM/8ABAAAM/8ABAAAM/8ABAAAM/8ABAAAM/8ABAAAM/8ABAAAM/8ABAAAM/8ABAAAM/8ABAAAM/8ABAAAM/8ABAAAM/8ABAAAM/8ABAAAM/8ABAAAM/8ABAAAM/8ABAAAM/8ABAAAM/8ABAAAM/8ABAAAM/8ABAAAM/8ABAAAM/8ABAAAM/8ABAAAM/8ABAAAM/8ABAAAM/8ABAAAM/8ABAAAM/8ABAAAM/8ABAAAM/8ABAAAM/8ABAAAM/8ABAAAM/8ABAAAM/8ABAAAM/8ABAAAM/8ABAAAAADNAgAAAADNAgAAAADNAgAAAADNAgAAAADNAgAAAADNAgAAAADNAgAAAADNAgAAAADNAgAAAADNAgAAAADNAgAAAADNAgAAAADNAgAAAADNAgAAAADNAgAAAADNAgAAAADNAgAAAADNAgAAAADNAgAAAADNAgAAAADNAgAAAADNAgAAAADNAgAAAADNAgAAAADNAgAAAADNAgAAAADNAgAAAADNAgAAAADNAgAAAADNAgAAAADNAgAAAADNAgAAAADNAgAAAADNAgAAAADNAgAAAADNAgAAmgEzB5r/mgEzB5r/mgEzB5r/mgEzB5r/mgEzB5r/mgEzB5r/mgEzB5r/mgEzB5r/mgEzB5r/mgEzB5r/mgEzB5r/mgEzB5r/mgEzB5r/mgEzB5r/mgEzB5r/mgEzB5r/mgEzB5r/mgEzB5r/mgEzB5r/mgEzB5r/mgEzB5r/mgEzB5r/mgEzB5r/mgEzB5r/mgEzB5r/mgEzB5r/mgEzB5r/mgEzB5r/mgEzB5r/mgEzB5r/mgEzB5r/mgEzB5r/mgEzB5r/mgEzB5r/mgEzB5r/mgEzB5r/Zv4zB5r/Zv4zB5r/Zv4zB5r/Zv4zB5r/Zv4zB5r/Zv4zB5r/Zv4zB5r/Zv4zB5r/Zv4zB5r/Zv4zB5r/Zv4zB5r/Zv4zB5r/Zv4zB5r/Zv4zB5r/Zv4zB5r/Zv4zB5r/Zv4zB5r/Zv4zB5r/Zv4zB5r/Zv4zB5r/Zv4zB5r/Zv4zB5r/Zv4zB5r/Zv4zB5r/Zv4zB5r/Zv4zB5r/Zv4zB5r/Zv4zB5r/Zv4zB5r/Zv4zB5r/Zv4zB5r/Zv4zB5r/Zv4zB5r/Zv4zB5r/Zv4zB5r/Zv4zB5r/AACaBwAAAACaBwAAAACaBwAAAACaBwAAAACaBwAAAACaBwAAAACaBwAAAACaBwAAAACaBwAAAACaBwAAAACaBwAAAACaBwAAAACaBwAAAACaBwAAAACaBwAAAACaBwAAAACaBwAAAACaBwAAAACaBwAAAACaBwAAAACaBwAAAACaBwAAAACaBwAAAACaBwAAAACaBwAAAACaBwAAAACaBwAAAACaBwAAAACaBwAAAACaBwAAAACaBwAAAACaBwAAAACaBwAAAACaBwAAAACaBwAAAACaBwAA');
  const qu = u16('LTTxQtU30UfVN/FC1TfRRy008UItNNFH1DPjQiwww0fUM8NHLDDDR9Qz40IsMONC2DeNSDA0vlTYN75UMDS+VNg3jUgwNI1IKjiNSNI7vlTSO41I0ju+VCo4jUgqOL5U2DO9VDAwjUgwML1UMDCNSNgzvVTYM41Izz+NSCc8vlTPP75UJzy+VM8/jUgnPI1IJyLqQs8ly0fPJepCzyXLRyci6kInIstH1SHuQi0ezkfVIc5HLR7OR9Uh7kItHu5C1yWOSC8ivlTXJb5ULyK+VNcljkgvIo5IMCaOSNgpv1TYKY5I2Cm/VDAmjkgwJr9U2SG+VDEejUgxHr5UMR6NSNkhvlTZIY1I2C2NSDAqvlTYLb5UMCq+VNgtjUgwKo1Iog3BTVIGElWiDRJVUgYSVaINwU1SBsFNrBvWQVsUz0ysG89MWxTPTKwb1kFbFNZBQg7VQb4TzUy+E9VBvhPNTEIO1UFCDs1Mpw3VQVcGzUynDc1MVwbNTKcN1UFXBtVBWwa1OawNBkGsDbU5rA0GQVsGtTlbBgZBSQDNTMUF1EFJANRBxQXUQUkAzUzFBc1MMTg5Mto7oj/aOzky2juiPzE4OTIxOKI/2T+iPzE8OTIxPKI/MTw5Mtk/oj/ZPzky3Dc4MjQ0oT/cN6E/NDShP9w3ODI0NDgy1jOhPy4wODIuMKE/LjA4MtYzoT/WMzgy2DPDLDAwpDHYM6QxMDCkMdgzwywwMMMsKzS3LNM3lzHTN7cs0zeXMSs0tywrNJcxMyY3MtspoD/bKTcy2ymgPzMmNzIzJqA/3S2gPzUqNzI1KqA/NSo3Mt0toD/dLTcy0iHILCkeqDHSIagxKR6oMdIhyCwpHsgsJCK8LMwlnDHMJbwszCWcMSQivCwkIpwx0iGgPykeNzIpHqA/KR43MtIhoD/SITcy2iU4MjIioD/aJaA/MiKgP9olODIyIjgydgjKFCYBCQsmAcoUJgEJC3YIyhR2CAkLVgh7AKYPOwqmD3sApg87ClYIewBWCDsKrA8IC/wWyBT8FggL/BbIFKwPCAusD8gUsQ8KC2EIyhSsD8gUYQjKFLEPCgthCAoLox8HC1IYyBSjH8gUUhjIFKMfBwtSGAcLnw9yFU8IMh+fDzIfTwgyH58PchVPCHIV');
  const mi = unpack('A4UDhQOFA4UDhQOFA/8D/wP/A/8D/wP/A+AD4APgA+AD4APgA8wDzAPMA8wDzAPMA6gDqAOoA6gDqAOoA7gDuAO4A7gDuAO4A4UDhQOFA4UDhQOFA/8D/wP/A/8D/wP/A+AD4APgA+AD4APgA8wDzAPMA8wDzAPMA6gDqAOoA6gDqAOoA7gDuAO4A7gDuAO4AYUBhQGFAYUBhQGFAbgBuAG4AbgBuAG4AcwBzAHMAcwBzAHMAeAB4AHgAeAB4AHgAf8B/wH/Af8B/wH/AagBqAGoAagBqAGoAswCzALMAswCzALMArgCuAK4ArgCuAK4AuAC4ALgAuAC4ALgAqgCqAKoAqgCqAKoAv8C/wL/Av8C/wL/AoUChQKFAoUChQKFAswCzALMAswCzALMArgCuAK4ArgCuAK4Av8C/wL/Av8C/wL/AoUChQKFAoUChQKFAqgCqAKoAqgCqAKoAuAC4ALgAuAC4ALgAKgAqACoAKgAqACoAP8A/wD/AP8A/wD/AMwAzADMAMwAzADMAOAA4ADgAOAA4ADgALgAuAC4ALgAuAC4AIUAhQCFAIUAhQCF');
  const n = 216;
  const position = new Float32Array(n * 3);
  const pivot = new Float32Array(n * 3);
  for (let k = 0; k < n * 3; k++) { position[k] = qp[k] * POS_Q; pivot[k] = qv[k] * POS_Q; }
  const uv = new Float32Array(n * 2);
  for (let k = 0; k < n * 2; k++) uv[k] = qu[k] * UV_Q;
  const zone = new Float32Array(n);
  const shade = new Float32Array(n);
  for (let k = 0; k < n; k++) { zone[k] = mi[k * 2]; shade[k] = mi[k * 2 + 1] / 255; }
  cached = { position, uv, pivot, zone, shade, index: u16('AAABAAIAAwAEAAUABgAHAAgACQAKAAsADAANAA4ADwAQABEAEgATABQAFQAWABcAGAAZABoAGwAcAB0AHgAfACAAIQAiACMAJAAlACYAJwAoACkAKgArACwALQAuAC8AMAAxADIAMwA0ADUANgA3ADgAOQA6ADsAPAA9AD4APwBAAEEAQgBDAEQARQBGAEcASABJAEoASwBMAE0ATgBPAFAAUQBSAFMAVABVAFYAVwBYAFkAWgBbAFwAXQBeAF8AYABhAGIAYwBkAGUAZgBnAGgAaQBqAGsAbABtAG4AbwBwAHEAcgBzAHQAdQB2AHcAeAB5AHoAewB8AH0AfgB/AIAAgQCCAIMAhACFAIYAhwCIAIkAigCLAIwAjQCOAI8AkACRAJIAkwCUAJUAlgCXAJgAmQCaAJsAnACdAJ4AnwCgAKEAogCjAKQApQCmAKcAqACpAKoAqwCsAK0ArgCvALAAsQCyALMAtAC1ALYAtwC4ALkAugC7ALwAvQC+AL8AwADBAMIAwwDEAMUAxgDHAMgAyQDKAMsAzADNAM4AzwDQANEA0gDTANQA1QDWANcA') };
  return cached;
}
